spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      database: test

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# custom properties
weather:
  source:
    sinoptik-url: "https://ua.sinoptik.ua"
    meteopost-url: " https://meteopost.com/weather/archive"
