spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        batch_size: 100
        order_inserts: true
#        generate_statistics: true
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/weather_archive"
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      database: test
      host: localhost
      port: 27017
#      username:
#      password:

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
#      isolation-level-for-create: default

# custom properties
weather:
  source:
    url: "https://ua.sinoptik.ua"
logging:
  level:
    org:
      springframework:
        batch:
          integration: debug
