spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      database: test

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
#      isolation-level-for-create: default

# custom properties
weather:
  source:
    url: "https://ua.sinoptik.ua"
